### ISSUE TITLE
[enhancement] Aim Assist

### ISSUE THREAD

**Issue by vos6434** [TeamMidnightDust/MidnightControlsExtra#1]
Could we get aim assist for mobs and blocks?

This mod is a great example
https://www.curseforge.com/minecraft/mc-mods/aim-assistance

**Comment by slushieuwu** [comment]
that mod seems to be being ported to fabric, so might as well wait for that rather than add it to this mod. but im not the dev of either mod so i cant control what the devs want to do

**Comment by Motschen** [comment]
There's a pre-release of the fabric version of Aim Assistance available now.
https://github.com/lilgallon/AimAssistance/releases/tag/1.0.0RC1-MC1.19.x
I think users that want it can just install that mod now, so I won't add it to MidnightControlsExtra and rather spend my time improving the existing features.
