### ISSUE TITLE
any plans on uppdating to 1.20.2?

### ISSUE THREAD

**Issue by temginson** [TeamMidnightDust/MidnightControlsExtra#2]
Hello,
I am a big fan of Midnight Controls Extra and I have really appreciated using it in my games. I am wondering if you are planning to update the mod to version 1.20.2? I am looking forward to being able to use all its fantastic features in the latest version of the game.

**Comment by Motschen** [comment]
MidnightControlsExtra is basically just an empty mod. MidnightControls checks for the presence of this mod and enables the extra features if it's found. That makes this MidnightControlsExtra version-independant, so you can use 1.0.0 on any Minecraft version MidnightControls runs on, including 1.20.2.

**Comment by temginson** [comment]
okay becuse its not showing up in modmenu in feather
________________________________
Från: Martin Prokoph ***@***.***>
Skickat: den 1 januari 2024 13:51
Till: TeamMidnightDust/MidnightControlsExtra ***@***.***>
Kopia: temginson ***@***.***>; Author ***@***.***>
Ämne: Re: [TeamMidnightDust/MidnightControlsExtra] any plans on uppdating to 1.20.2? (Issue #2)


MidnightControlsExtra is basically just an empty mod. MidnightControls checks for the presence of this mod and enables the extra features if it's found. That makes this MidnightControlsExtra version-independant, so you can use 1.0.0 on any Minecraft version MidnightControls runs on, including 1.20.2.
